export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_ACTIVENAME = 'CHANGE_ACTIVENAME' //菜单激活项
export const CHANGE_CURRENT_PATH = 'CHANGE_CURRENT_PATH'
export const CHANGE_SEC_BREAD = 'CHANGE_SEC_BREAD'
export const CHANGE_THIRD_BREAD = 'CHANGE_THIRD_BREAD'
export const CHANGE_FORTH_BREAD = 'CHANGE_FORTH_BREAD'
export const CHANGE_FORM = 'CHANGE_FORM'
export const CHANGE_SPIN_SHOW = 'CHANGE_SPIN_SHOW'

export const CHANGE_FORM_COLL = 'CHANGE_FORM_COLL'
export const CHANGE_COLL_STATUS = 'CHANGE_COLL_STATUS'

export const MORE_THAN_THREEDAYS = 'MORE_THAN_THREEDAYS'